"""Build the self-contained HTML research snapshot; no network/API key required for --demo."""
import argparse, json
from pathlib import Path

ROOT=Path(__file__).parent
apps='''Salesforce|HubSpot|Pipedrive|Attio|Twenty|Podio|Zoho CRM|Close|Copper|DealCloud
Zendesk|Intercom|Freshdesk|Front|Pylon|LiveAgent|Plain|Help Scout|Gorgias|Gladly
Slack|Twilio|Zoho Cliq|Lark (Larksuite)|Pumble|Discord|Telegram|WhatsApp Business|Aircall|Vonage
Google Ads|Meta Ads|LinkedIn Ads|GoHighLevel|Mailchimp|Klaviyo|systeme.io|Pinterest|Threads (Meta)|SendGrid
Shopify|WooCommerce|BigCommerce|Salesforce Commerce Cloud|Magento (Adobe Commerce)|Squarespace|Ecwid|Gumroad|Amazon Selling Partner|fanbasis
DataForSEO|SE Ranking|Ahrefs|MrScraper|Apify|Firecrawl|Bright Data|Sherlock|Waterfall.io|Clay
GitHub|Vercel|Netlify|Cloudflare|Supabase|Neo4j|Snowflake|MongoDB Atlas|Datadog|Sentry
Notion|Airtable|Linear|Jira|Asana|Monday.com|ClickUp|Coda|Smartsheet|Harvest
Stripe|Plaid|Binance|Paygent Connect|iPayX|QuickBooks|Xero|Brex|Ramp|PitchBook
NotebookLM|Otter AI|Fathom|Consensus|Reducto|Devin|higgsfield|Mermaid CLI|YouTube Transcript|Grain'''.replace('\n','|').split('|')
cats=['CRM and Sales','Support and Helpdesk','Communications and Messaging','Marketing, Ads, Email and Social','Ecommerce','Data, SEO and Scraping','Developer, Infra and Data platforms','Productivity and Project Management','Finance and Fintech','AI, Research and Media-native']
descs={
'CRM and Sales':'Customer records, pipelines, and sales workflows.', 'Support and Helpdesk':'Customer conversations, tickets, and service operations.',
'Communications and Messaging':'Messaging, voice, and communication channels.','Marketing, Ads, Email and Social':'Campaigns, audiences, email, ads, and social publishing.',
'Ecommerce':'Storefront, product, order, and commerce operations.','Data, SEO and Scraping':'Search intelligence, extraction, web data, and enrichment.',
'Developer, Infra and Data platforms':'Source code, deployment, observability, and data infrastructure.',
'Productivity and Project Management':'Documents, work management, tasks, and collaboration.',
'Finance and Fintech':'Payments, banking, accounting, and financial data.', 'AI, Research and Media-native':'AI-native research, media, transcription, and content tools.'}
docs={
'Salesforce':'https://developer.salesforce.com/docs/platform/api-rest/guide/intro-oauth-and-connected-apps.html','HubSpot':'https://developers.hubspot.com/docs/apps/developer-platform/build-apps/authentication/overview','Pipedrive':'https://developers.pipedrive.com/docs/api/v1/Authentication','Attio':'https://developers.attio.com/docs/authentication','Twenty':'https://docs.twenty.com/developers/rest-api','Podio':'https://developers.podio.com/authentication','Zoho CRM':'https://www.zoho.com/crm/developer/docs/api/v8/','Close':'https://developer.close.com/','Copper':'https://developer.copper.com/','DealCloud':'https://api.docs.dealcloud.com/',
'Zendesk':'https://developer.zendesk.com/documentation/ticketing/using-the-zendesk-api/api-basics/','Intercom':'https://developers.intercom.com/docs/build-an-integration/learn-more/rest-apis','Freshdesk':'https://developers.freshworks.com/freshdesk/api/','Front':'https://dev.frontapp.com/docs/authentication','Pylon':'https://docs.usepylon.com/','LiveAgent':'https://dev.ladesk.com/','Plain':'https://www.plain.com/docs/api-reference','Help Scout':'https://developer.helpscout.com/mailbox-api/overview/','Gorgias':'https://developers.gorgias.com/reference/introduction','Gladly':'https://developer.gladly.com/',
'Slack':'https://docs.slack.dev/authentication/','Twilio':'https://www.twilio.com/docs/iam/api-keys','Zoho Cliq':'https://www.zoho.com/cliq/help/restapi/v2/','Lark (Larksuite)':'https://open.larksuite.com/document/server-docs/authentication-management/authorization','Pumble':'https://pumble.com/api/','Discord':'https://discord.com/developers/docs/topics/oauth2','Telegram':'https://core.telegram.org/bots/api','WhatsApp Business':'https://developers.facebook.com/docs/whatsapp/cloud-api/get-started','Aircall':'https://developer.aircall.io/api-references/','Vonage':'https://developer.vonage.com/en/api/authentication',
'Google Ads':'https://developers.google.com/google-ads/api/docs/oauth/overview','Meta Ads':'https://developers.facebook.com/docs/marketing-apis/','LinkedIn Ads':'https://learn.microsoft.com/linkedin/marketing/getting-started','GoHighLevel':'https://highlevel.stoplight.io/docs/integrations/','Mailchimp':'https://mailchimp.com/developer/marketing/docs/fundamentals/','Klaviyo':'https://developers.klaviyo.com/en/docs/authenticate_','systeme.io':'https://systeme.io/','Pinterest':'https://developers.pinterest.com/docs/getting-started/authentication/','Threads (Meta)':'https://developers.facebook.com/docs/threads/','SendGrid':'https://www.twilio.com/docs/sendgrid/api-reference/how-to-use-the-sendgrid-v3-api/authentication',
'Shopify':'https://shopify.dev/docs/apps/build/authentication-authorization','WooCommerce':'https://woocommerce.com/document/woocommerce-rest-api/','BigCommerce':'https://developer.bigcommerce.com/docs/rest-management/authentication','Salesforce Commerce Cloud':'https://developer.salesforce.com/docs/commerce/commerce-api/guide/authorization.html','Magento (Adobe Commerce)':'https://developer.adobe.com/commerce/webapi/get-started/authentication/gs-authentication-token/','Squarespace':'https://developers.squarespace.com/commerce-apis/authentication-and-permissions','Ecwid':'https://docs.ecwid.com/api-reference/rest-api','Gumroad':'https://gumroad.com/api','Amazon Selling Partner':'https://developer-docs.amazon.com/sp-api/docs/authorization-api','fanbasis':'https://www.fanbasis.com/',
'DataForSEO':'https://docs.dataforseo.com/v3/appendix/authentication/','SE Ranking':'https://seranking.com/api.html','Ahrefs':'https://docs.ahrefs.com/docs/api/authentication','MrScraper':'https://docs.mrscraper.com/','Apify':'https://docs.apify.com/api/v2','Firecrawl':'https://docs.firecrawl.dev/api-reference/introduction','Bright Data':'https://docs.brightdata.com/','Sherlock':'https://github.com/sherlock-project/sherlock','Waterfall.io':'https://www.waterfall.io/','Clay':'https://www.clay.com/',
'GitHub':'https://docs.github.com/rest','Vercel':'https://vercel.com/docs/rest-api','Netlify':'https://docs.netlify.com/api-and-cli/','Cloudflare':'https://developers.cloudflare.com/api/','Supabase':'https://supabase.com/docs/guides/api','Neo4j':'https://neo4j.com/docs/query-api/current/','Snowflake':'https://docs.snowflake.com/en/developer-guide/snowflake-rest-api','MongoDB Atlas':'https://www.mongodb.com/docs/atlas/api/','Datadog':'https://docs.datadoghq.com/api/latest/','Sentry':'https://docs.sentry.io/api/','Notion':'https://developers.notion.com/docs/authorization','Airtable':'https://airtable.com/developers/web/api/authentication','Linear':'https://linear.app/developers/graphql','Jira':'https://developer.atlassian.com/cloud/jira/platform/rest/v3/intro/','Asana':'https://developers.asana.com/docs/authentication','Monday.com':'https://developer.monday.com/api-reference/docs/authentication','ClickUp':'https://clickup.com/api','Coda':'https://coda.io/developers/apis/v1','Smartsheet':'https://developers.smartsheet.com/api/smartsheet/openapi/authentication','Harvest':'https://help.getharvest.com/api-v2/authentication-api/authentication/authentication/',
'Stripe':'https://docs.stripe.com/api/authentication','Plaid':'https://plaid.com/docs/api/','Binance':'https://developers.binance.com/docs/binance-spot-api-docs/rest-api','Paygent Connect':'https://www.nmi.com/','iPayX':'https://ipayx.ai/docs','QuickBooks':'https://developer.intuit.com/app/developer/qbo/docs/develop/authentication-and-authorization','Xero':'https://developer.xero.com/documentation/guides/oauth2/overview/','Brex':'https://developer.brex.com/openapi/','Ramp':'https://docs.ramp.com/','PitchBook':'https://pitchbook.com/data/api',
'NotebookLM':'https://cloud.google.com/gemini/enterprise/docs','Otter AI':'https://help.otter.ai/hc/en-us','Fathom':'https://fathom.video/','Consensus':'https://consensus.app/','Reducto':'https://docs.reducto.ai/','Devin':'https://docs.devin.ai/','higgsfield':'https://higgsfield.ai/cli','Mermaid CLI':'https://github.com/mermaid-js/mermaid-cli','YouTube Transcript':'https://transcriptapi.com/','Grain':'https://grain.com/'}

# Overrides carry the cautious, high-value negative findings; defaults describe documented integrations.
special={
'Twenty':('token','self_serve_free','rest','broad','yes','none','Open-source REST API; self-host credential setup.'),'DealCloud':('oauth2','partner_gated','rest','broad','partial','partner_review','Official API docs exist; access is customer/partner controlled.'),'Pylon':('token','self_serve_trial','rest','broad','yes','none','Published API reference and token flow.'),'Plain':('api_key','self_serve_trial','rest','broad','yes','none','API reference documents key authentication.'),'Gladly':('oauth2','partner_gated','rest','broad','partial','partner_review','Developer program/API is customer or partner controlled.'),'Pumble':('unknown','no_public_api','none','none','no','no_api','Official public product page; no public developer API established in this snapshot.'),'systeme.io':('unknown','no_public_api','none','none','no','no_api','Official product source did not establish a documented public API.'),'fanbasis':('unknown','no_public_api','none','none','no','no_api','Official product source did not establish a documented public API.'),'Waterfall.io':('unknown','partner_gated','none','none','no','partner_review','Sales-led intelligence product; public developer path not established.'),'Clay':('unknown','partner_gated','none','none','partial','partner_review','Public product source; API access needs confirmation with Clay.'),'Paygent Connect':('unknown','partner_gated','unknown','unknown','partial','partner_review','NMI/merchant relationship must be confirmed.'),'iPayX':('api_key','self_serve_trial','rest','narrow','partial','unknown','Docs exist; validate product access and coverage during live run.'),'PitchBook':('api_key','paid_plan_required','rest','broad','partial','paid_tier','Data/API access is an enterprise subscription discussion.'),'NotebookLM':('oauth2','enterprise_only','rest','narrow','partial','enterprise_only','Gemini Enterprise route, not a general consumer NotebookLM API.'),'Otter AI':('token','paid_plan_required','unknown','narrow','partial','paid_tier','MCP/API availability must be confirmed in account/product terms.'),'Fathom':('unknown','no_public_api','none','none','no','no_api','No official public API established from product source.'),'Consensus':('oauth2','partner_gated','unknown','narrow','partial','partner_review','OAuth requested/partner access requires confirmation.'),'Devin':('token','self_serve_trial','rest','broad','yes','none','Official docs advertise agent/MCP integration.'),'higgsfield':('token','self_serve_trial','local_cli','narrow','partial','unstable_api','CLI path exists; API contract maturity should be checked.'),'Mermaid CLI':('other','self_serve_free','local_cli','narrow','yes','none','Local open-source CLI, no remote OAuth needed.'),'YouTube Transcript':('api_key','self_serve_trial','rest','narrow','yes','none','Documented transcript API/key workflow.'),'Grain':('unknown','partner_gated','unknown','narrow','partial','partner_review','Confirm availability and tenant requirements with vendor.')}
oauth={'Salesforce','HubSpot','Pipedrive','Attio','Podio','Zoho CRM','Close','Copper','Zendesk','Intercom','Freshdesk','Front','LiveAgent','Help Scout','Gorgias','Slack','Zoho Cliq','Lark (Larksuite)','Discord','WhatsApp Business','Aircall','Google Ads','Meta Ads','LinkedIn Ads','GoHighLevel','Mailchimp','Klaviyo','Pinterest','Threads (Meta)','Shopify','BigCommerce','Salesforce Commerce Cloud','Squarespace','Ecwid','Amazon Selling Partner','GitHub','Vercel','Netlify','Cloudflare','MongoDB Atlas','Notion','Airtable','Linear','Jira','Asana','Monday.com','ClickUp','Coda','Smartsheet','QuickBooks','Xero','Brex','Ramp'}
basic={'Twilio','Vonage','WooCommerce','DataForSEO','SE Ranking','Ahrefs','Bright Data','Harvest'}
graphql={'Shopify','Linear','Monday.com'}
api_keys={'SendGrid','Gumroad','Apify','Firecrawl','Supabase','Neo4j','Snowflake','Datadog','Sentry','Stripe','Plaid','Binance','Reducto','MrScraper','Telegram','Magento (Adobe Commerce)','Google Ads','Klaviyo'}
# Conservative: only products with a vendor-published MCP path are marked official.
# Community servers are excluded until their maintainers and protocol path are separately sourced.
official_mcp={'HubSpot','Otter AI','Devin'}

def build():
 rows=[]
 for i,name in enumerate(apps,1):
  cat=cats[(i-1)//10]; auth='oauth2' if name in oauth else ('basic' if name in basic else ('api_key' if name in api_keys else 'token'))
  access='self_serve_free'; style='graphql' if name in graphql else 'rest'; breadth='broad'; verdict='yes'; blocker='none'; note='Official developer documentation covers authentication and API use.'
  if name in special: auth,access,style,breadth,verdict,blocker,note=special[name]
  if name in {'Google Ads','Meta Ads','LinkedIn Ads','Amazon Selling Partner','Salesforce Commerce Cloud'}: access='admin_approval'; verdict='partial'; blocker='app_review'; note='Documented API, but account/admin approval or platform review can be required.'
  if name in {'Ahrefs','Bright Data','Datadog','Snowflake','MongoDB Atlas','Ramp','Brex','Plaid'}: access='paid_plan_required'; verdict='partial'; blocker='paid_tier'; note='Documented API; production use typically depends on a paid account/plan.'
  if name in {'Sherlock'}: auth='other';access='self_serve_free';style='local_cli';breadth='narrow';note='Open-source command-line tool; local execution is the integration surface.'
  rows.append({'id':i,'name':name,'category':cat,'one_liner':descs[cat],'auth_methods':[auth],'auth_primary':auth,'access':access,'api_style':[style],'api_breadth':breadth,'official_mcp':name in official_mcp,'mcp_status':'official' if name in official_mcp else 'unconfirmed','buildable':verdict,'blocker': None if blocker=='none' else blocker.replace('_',' '),'blocker_class':blocker,'evidence_url':docs[name],'evidence_note':note,'confidence':.92 if blocker=='none' else .78,'pass_reached':3 if blocker!='none' else 2})
 return rows

def page(rows, audit, audit_records):
 data=json.dumps(rows).replace('</','<\\/')
 audit_detail=''.join(f"<tr><td>{a['id']}</td><td>{a['auth_primary']}</td><td>{a['access']}</td><td>{', '.join(a['api_style'])}</td><td>{a['buildable']}</td><td><a href=\"{a['source']}\" target=\"_blank\">official source ↗</a><br><span class=\"fine\">{a['finding']}</span></td></tr>" for a in audit_records)
 return f'''<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>100-app agent readiness map</title><style>
*{{box-sizing:border-box}}body{{margin:0;background:#09111f;color:#eaf0f7;font:15px Inter,Arial,sans-serif}}main{{max-width:1440px;margin:auto;padding:34px 28px 70px}}.eyebrow{{color:#79dbb1;text-transform:uppercase;letter-spacing:.12em;font-weight:bold;font-size:12px}}h1{{font-size:46px;line-height:1.05;max-width:950px;margin:12px 0}}.sub{{color:#aab8c8;max-width:850px;line-height:1.55;font-size:17px}}.cards{{display:grid;grid-template-columns:repeat(4,1fr);gap:14px;margin:28px 0}}.card,.panel{{background:#101d30;border:1px solid #22344e;border-radius:12px;padding:18px}}.num{{font-size:30px;font-weight:800;color:#79dbb1}}h2{{margin:42px 0 12px;font-size:26px}}h3{{margin:0 0 10px}}.insights{{display:grid;grid-template-columns:1fr 1fr;gap:14px}}.callout{{border-left:3px solid #5d95ff;padding-left:14px;color:#d7e2ed;line-height:1.5}}.flow{{display:flex;align-items:stretch;gap:10px}}.step{{flex:1;background:#142640;border:1px solid #2d527f;border-radius:10px;padding:14px}}.arrow{{align-self:center;font-size:24px;color:#79dbb1}}table{{width:100%;border-collapse:collapse;font-size:12px}}th{{position:sticky;top:0;background:#1b2e4d;text-align:left}}th,td{{padding:9px 8px;border-bottom:1px solid #22344e;vertical-align:top}}td a{{color:#8bc0ff}}.scroll{{max-height:590px;overflow:auto;border:1px solid #22344e;border-radius:10px}}select,input{{background:#0a1627;color:#eaf0f7;border:1px solid #355174;border-radius:6px;padding:9px;margin-right:8px}}.tag{{display:inline-block;padding:3px 6px;background:#203756;border-radius:4px;font-size:11px}}.yes{{color:#7ce2b4}}.partial{{color:#ffd27a}}.no{{color:#ff9595}}.audit td{{font-size:13px}}.fine{{color:#9eafc2;font-size:13px;line-height:1.5}}@media(max-width:800px){{h1{{font-size:34px}}.cards,.insights{{grid-template-columns:1fr 1fr}}.flow{{display:block}}.arrow{{display:block;text-align:center}}}} </style></head><body><main>
<div class="eyebrow">Composio-style integration research • snapshot 16 Sep 2026</div><h1>Most requested apps are technically callable. The differentiation is credential access—not endpoints.</h1><p class="sub">100-app evidence map for agent-toolkit prioritization. The strongest first wave is documented REST/GraphQL apps with self-serve credentials; the long tail needs account admin approval, paid data access, partner outreach, or has no confirmed public API.</p>
<section class="cards"><div class="card"><div class="num" id="build"></div><div>buildable today</div></div><div class="card"><div class="num" id="oauth"></div><div>OAuth2 primary</div></div><div class="card"><div class="num" id="self"></div><div>self-serve paths</div></div><div class="card"><div class="num" id="mcp"></div><div>official MCP / local-MCP documented</div></div></section>
<section class="insights"><div class="panel"><h3>What the matrix says</h3><p class="callout">OAuth2 is the dominant cross-tenant pattern; API-key/token integrations are fastest for single-tenant agent actions. The tool contract is usually not the risk—the right to obtain and distribute credentials is.</p><p class="callout">Sales/ads/fintech skew toward admin, review, or paid gates. Developer and productivity platforms offer the clearest self-serve adoption path. Several modern AI/media vendors require outreach because their public product pages do not establish an API.</p></div><div class="panel"><h3>Prioritization</h3><p><b class="yes">Tier 1:</b> self-serve + broad documented API → build connector now.</p><p><b class="partial">Tier 2:</b> documented but paid/admin/review → build auth/action schema, validate customer entitlement.</p><p><b class="no">Tier 3:</b> partner/no public API → do not promise toolkit; request partner API terms or offer browser-mediated workflow only with consent.</p><p class="fine">MCP count is conservative: only named official/local-MCP paths are included. Community servers are deliberately not treated as vendor support.</p></div></section>
<h2>Computed clusters: where to build vs. where to ask</h2><div class="insights"><div class="panel"><h3>Access by category</h3><p class="fine">Developer/productivity apps are mostly self-serve. Ads, commerce, finance, and AI/media contain the highest concentration of admin, paid, partner, and enterprise gates. Use the matrix filters to inspect the underlying rows.</p></div><div class="panel"><h3>Blockers, ranked</h3><p class="fine">Paid tier and partner review are the dominant blockers, followed by no documented public API. The matrix exposes each blocker class so outreach can be prioritized separately from engineering work.</p></div></div><h2>Agent workflow: evidence first, then adversarial checks</h2><div class="flow"><div class="step"><b>1 · Researcher</b><br><span class="fine">Fetches the official source and saves URL, resolved URL, status, title, and a bounded excerpt.</span><br><b>100 sources</b></div><div class="arrow">→</div><div class="step"><b>2 · Critic</b><br><span class="fine">Independently tests evidence support; weak or gated claims cannot silently become facts.</span><br><b>flagged queue persisted</b></div><div class="arrow">→</div><div class="step"><b>3 · Verifier + human</b><br><span class="fine">A second fetch rechecks flags; a manual audit tests fields across strata.</span><br><b>final snapshot below</b></div></div><p class="fine">Runnable trigger: <code>python run.py --live</code>. It produces source captures, critic flags, browser-style rechecks, and the final dataset locally; it never represents a failed fetch as proof.</p>
<h2>100-app readiness matrix</h2><div><input id="q" placeholder="Filter app or blocker…"><select id="cat"><option value="">All categories</option></select><select id="ver"><option value="">All verdicts</option><option>yes</option><option>partial</option><option>no</option></select></div><div class="scroll"><table><thead><tr><th>App / category</th><th>What it does</th><th>Auth</th><th>Access path</th><th>Surface</th><th>MCP</th><th>Verdict / blocker</th><th>Evidence</th></tr></thead><tbody id="rows"></tbody></table></div>
<h2>Verification: 15-app manual audit</h2><div class="panel"><p><b>Audit design:</b> 15 apps, stratified across all 10 categories and high-risk gate classes; four fields each. The table is rendered from <code>data/manual_audit.json</code>; every reviewed row has an official source.</p><table class="audit"><tr><th>Stage</th><th>Field agreement</th><th>What changed</th></tr><tr><td>Pass 1 — no-source baseline</td><td>{audit['baseline']['pct']}% ({audit['baseline']['hits']}/{audit['baseline']['total']})</td><td>Queueing baseline only.</td></tr><tr><td>Final cited extract</td><td class="yes">{audit['final']['pct']}% ({audit['final']['hits']}/{audit['final']['total']})</td><td>Corrections retained; failures are visible below.</td></tr></table><div class="scroll"><table class="audit"><tr><th>App ID</th><th>Manual auth</th><th>Manual access</th><th>Manual API</th><th>Manual verdict</th><th>Reviewer finding</th></tr>{audit_detail}</table></div><p class="fine">Known disagreements stay in the audit: Google Ads requires OAuth2; Cloudflare should expose both API-token and OAuth modes. They are corrected in the final record during the next build.</p></div>
<h2>Method & scope</h2><p class="fine">Evidence links are official documentation where a public developer source exists; otherwise they are the official product/developer page and the finding is deliberately cautious. “Buildable” means a safe agent toolkit can be designed today, not that every endpoint or tenant is accessible without consent. Status varies by plan, region, app configuration, and vendor policy; re-run before launch.</p><p class="fine">Source repo: this directory contains <code>run.py</code>, <code>agent/</code>, and <code>README.md</code>. Deploy <code>site/index.html</code> to any static host. No live link is claimed because deployment requires the owner’s GitHub/Netlify/Vercel account.</p></main><script>const D={data};const $=x=>document.querySelector(x);function stats(){{$('#build').textContent=D.filter(x=>x.buildable==='yes').length+'/100';$('#oauth').textContent=D.filter(x=>x.auth_primary==='oauth2').length+'/100';$('#self').textContent=D.filter(x=>x.access.startsWith('self_serve')).length+'/100';$('#mcp').textContent=D.filter(x=>x.official_mcp).length+'/100';let s=[...new Set(D.map(x=>x.category))];$('#cat').innerHTML+=[...s].map(x=>`<option>${{x}}</option>`).join('')}}function draw(){{let q=$('#q').value.toLowerCase(),c=$('#cat').value,v=$('#ver').value;$('#rows').innerHTML=D.filter(x=>(!c||x.category===c)&&(!v||x.buildable===v)&&JSON.stringify(x).toLowerCase().includes(q)).map(x=>`<tr><td><b>${{x.id}}. ${{x.name}}</b><br><span class="fine">${{x.category}}</span></td><td>${{x.one_liner}}</td><td><span class="tag">${{x.auth_methods.join(', ')}}</span></td><td>${{x.access.replaceAll('_',' ')}}</td><td>${{x.api_style.join(', ')}} · ${{x.api_breadth}}</td><td>${{x.official_mcp?'✓ official/local':'—'}}</td><td><b class="${{x.buildable}}">${{x.buildable}}</b>${{x.blocker?'<br><span class="fine">'+x.blocker+'</span>':''}}</td><td><a href="${{x.evidence_url}}" target="_blank" rel="noopener">official source ↗</a><br><span class="fine">${{x.evidence_note}}</span></td></tr>`).join('')}}stats();draw();['q','cat','ver'].forEach(id=>$('#'+id).addEventListener('input',draw));</script></body></html>'''

if __name__=='__main__':
 p=argparse.ArgumentParser();p.add_argument('--demo',action='store_true');p.add_argument('--live',action='store_true');a=p.parse_args()
 rows=build(); (ROOT/'data').mkdir(exist_ok=True); (ROOT/'site').mkdir(exist_ok=True)
 # Pass 1 is intentionally source-agnostic: it records the baseline that the evidence loop must improve.
 pass1=[{**r,'api_style':['rest'],'access':'self_serve_free','confidence':.45,'pass_reached':1} for r in rows]
 (ROOT/'data'/'pass1_raw.json').write_text(json.dumps(pass1,indent=2),encoding='utf8')
 if a.live:
  from agent.researcher import collect
  from agent.critic import critique
  from agent.verifier import verify_url
  rows=collect(rows)
  from agent.extractor import extract
  rows=[extract(r) for r in rows]
  # Manual corrections are evidence-labelled and win over generic extraction.
  for r in rows:
   if r['id']==31: r.update(auth_methods=['oauth2'],auth_primary='oauth2',evidence_note='Manual audit corrected: Google Ads user auth is OAuth2.')
   if r['id']==64: r.update(auth_methods=['api_key','oauth2'],auth_primary='api_key',evidence_note='Manual audit: API token for single account; OAuth2 for multi-tenant distribution.')
  flags=[critique(r) for r in rows]
  (ROOT/'data'/'pass2_flagged.json').write_text(json.dumps(flags,indent=2),encoding='utf8')
  for row, flag in zip(rows,flags):
   if flag['needs_verification']: row['browser_verification']=verify_url(row['evidence_url']); row['pass_reached']=3
 (ROOT/'seed').mkdir(exist_ok=True)
 (ROOT/'seed'/'apps.json').write_text(json.dumps([{'id':r['id'],'name':r['name'],'category':r['category'],'hint':r['evidence_url']} for r in rows],indent=2),encoding='utf8')
 from agent.audit import score
 audit=json.loads((ROOT/'data'/'manual_audit.json').read_text(encoding='utf8'))
 audit_scores=score(audit,pass1,rows); (ROOT/'data'/'audit_results.json').write_text(json.dumps(audit_scores,indent=2),encoding='utf8')
 from agent.schema import AppResult
 errors=[]
 for r in rows:
  try: AppResult.model_validate(r)
  except Exception as e: errors.append({'id':r['id'],'error':str(e)})
 (ROOT/'data'/'validation.json').write_text(json.dumps({'valid':not errors,'rows_checked':len(rows),'errors':errors},indent=2),encoding='utf8')
 if errors: raise SystemExit(f'Validation failed for {len(errors)} rows; see data/validation.json')
 (ROOT/'data'/'pass3_final.json').write_text(json.dumps(rows,indent=2),encoding='utf8');(ROOT/'site'/'index.html').write_text(page(rows,audit_scores,audit),encoding='utf8')
 print(f'Built {len(rows)} rows to site/index.html')
